"""Add enums to client table

Revision ID: 70093b34ac09
Revises: e979462e9d55
Create Date: 2026-05-26 11:23:19.818630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70093b34ac09'
down_revision: Union[str, Sequence[str], None] = 'e979462e9d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('WAITING_ANALYSIS', 'PROCESSED', name='clientstatus'),
               existing_nullable=False)
    op.alter_column('clients', 'prioridade',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('HIGH', 'NORMAL', name='clientpriority'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'prioridade',
               existing_type=sa.Enum('HIGH', 'NORMAL', name='clientpriority'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('clients', 'status',
               existing_type=sa.Enum('WAITING_ANALYSIS', 'PROCESSED', name='clientstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
