"""Add processed events table and timestamp to clients table and enum

Revision ID: 9bdb8d886bbd
Revises: e979462e9d55
Create Date: 2026-05-26 14:31:30.834198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bdb8d886bbd'
down_revision: Union[str, Sequence[str], None] = 'e979462e9d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('clients', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('WAITING_ANALYSIS', 'PROCESSED', name='clientstatus'),
               existing_nullable=False)
    op.alter_column('clients', 'prioridade',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('HIGH', 'NORMAL', name='clientpriority'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'prioridade',
               existing_type=sa.Enum('HIGH', 'NORMAL', name='clientpriority'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('clients', 'status',
               existing_type=sa.Enum('WAITING_ANALYSIS', 'PROCESSED', name='clientstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'created_at')
    # ### end Alembic commands ###
