"""Add processed_events table

Revision ID: c4c675e88819
Revises: e838ea9b9a55
Create Date: 2026-05-26 14:56:08.567875

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4c675e88819"
down_revision: Union[str, Sequence[str], None] = "e838ea9b9a55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(length=120), nullable=False),
        sa.Column("card_id", sa.String(length=120), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processed_events_event_id"),
        "processed_events",
        ["event_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processed_events_event_id"), table_name="processed_events")
    op.drop_table("processed_events")
    # ### end Alembic commands ###
