"""remove redudant index from event_id

Revision ID: c8b897a13581
Revises: c4c675e88819
Create Date: 2026-05-26 15:50:42.690339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b897a13581'
down_revision: Union[str, Sequence[str], None] = 'c4c675e88819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.create_unique_constraint(None, 'processed_events', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processed_events', type_='unique')
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=True)
    # ### end Alembic commands ###
