"""Add timestamp to clients table

Revision ID: e838ea9b9a55
Revises: e979462e9d55
Create Date: 2026-05-26 14:54:08.675542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e838ea9b9a55'
down_revision: Union[str, Sequence[str], None] = 'e979462e9d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'created_at')
    # ### end Alembic commands ###
