"""create clients table

Revision ID: e979462e9d55
Revises:
Create Date: 2026-05-26 10:14:00.869580

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e979462e9d55"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cliente_nome", sa.String(length=100), nullable=False),
        sa.Column("cliente_email", sa.String(length=120), nullable=False),
        sa.Column("tipo_solicitacao", sa.String(length=120), nullable=False),
        sa.Column(
            "valor_patrimonio", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("prioridade", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cliente_email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clients")
    # ### end Alembic commands ###
